-- ============================================================
-- HORAS-IM: COMPLETE SUPABASE SETUP SCRIPT
-- Jalankan file ini SEKALI di Supabase SQL Editor
-- Mencakup: Extension, Tabel, Storage Bucket, Policies
-- ============================================================


-- ============================================================
-- STEP 1: Aktifkan Extension yang Dibutuhkan
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ============================================================
-- STEP 2: Tambah kolom urutan_penggabungan di tabel sections
-- (Abaikan error jika kolom sudah ada)
-- ============================================================
ALTER TABLE sections
  ADD COLUMN IF NOT EXISTS urutan_penggabungan int DEFAULT 99;

-- Set urutan seksi
UPDATE sections SET urutan_penggabungan = 1 WHERE name ILIKE '%inteldakim%';
UPDATE sections SET urutan_penggabungan = 2 WHERE name ILIKE '%lalintalkim%';
UPDATE sections SET urutan_penggabungan = 3 WHERE name ILIKE '%tikim%';
UPDATE sections SET urutan_penggabungan = 4 WHERE name ILIKE '%tata usaha%' OR name ILIKE '%fasilitatif%';


-- ============================================================
-- STEP 3: Tabel app_users
-- ============================================================
CREATE TABLE IF NOT EXISTS app_users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama            text NOT NULL,
  email           text NOT NULL UNIQUE,
  password_hash   text NOT NULL,
  role            text NOT NULL CHECK (role IN ('super_admin','admin_seksi')),
  seksi_id        bigint REFERENCES sections(id) ON DELETE SET NULL,
  is_active       boolean DEFAULT true,
  last_login      timestamp with time zone,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);


-- ============================================================
-- STEP 4: Tabel laporan_bulanan
-- ============================================================
CREATE TABLE IF NOT EXISTS laporan_bulanan (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seksi_id        bigint NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  bulan           int NOT NULL CHECK (bulan BETWEEN 1 AND 12),
  tahun           int NOT NULL CHECK (tahun >= 2020),

  file_name       text,
  file_path       text,
  file_url        text,
  file_size       bigint,
  file_type       text,   -- 'docx' atau 'pdf'

  status          text NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft','Dikirim','Perlu Revisi','Disetujui','Final')),

  catatan_revisi  text,
  submitted_at    timestamp with time zone,
  submitted_by    bigint REFERENCES app_users(id) ON DELETE SET NULL,
  reviewed_by     bigint REFERENCES app_users(id) ON DELETE SET NULL,
  approved_at     timestamp with time zone,
  final_locked    boolean DEFAULT false,

  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL,

  UNIQUE(seksi_id, bulan, tahun)
);

CREATE INDEX IF NOT EXISTS idx_laporan_seksi_id       ON laporan_bulanan(seksi_id);
CREATE INDEX IF NOT EXISTS idx_laporan_status          ON laporan_bulanan(status);
CREATE INDEX IF NOT EXISTS idx_laporan_bulan_tahun     ON laporan_bulanan(bulan, tahun);


-- ============================================================
-- STEP 5: Tabel activity_logs
-- ============================================================
CREATE TABLE IF NOT EXISTS activity_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint REFERENCES app_users(id) ON DELETE SET NULL,
  user_name   text,
  action      text NOT NULL,
  entity_type text,
  entity_id   bigint,
  detail      text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user    ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at DESC);


-- ============================================================
-- STEP 6: Insert akun default
-- ============================================================

-- Super Admin
INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Super Administrator',
  'superadmin@horas-im.local',
  encode(digest('Admin@2026', 'sha256'), 'hex'),
  'super_admin',
  NULL
ON CONFLICT (email) DO NOTHING;

-- Admin Inteldakim
INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Inteldakim',
  'inteldakim@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%inteldakim%' LIMIT 1
ON CONFLICT (email) DO NOTHING;

-- Admin Lalintalkim
INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Lalintalkim',
  'lalintalkim@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%lalintalkim%' LIMIT 1
ON CONFLICT (email) DO NOTHING;

-- Admin Tikim
INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Tikim',
  'tikim@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%tikim%' LIMIT 1
ON CONFLICT (email) DO NOTHING;

-- Admin Tata Usaha
INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Tata Usaha',
  'tu@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE (s.name ILIKE '%tata usaha%' OR s.name ILIKE '%fasilitatif%') LIMIT 1
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- STEP 7: Storage Bucket untuk file laporan
-- ============================================================

-- Buat bucket 'laporan-bulanan' (public agar URL file bisa diakses langsung)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'laporan-bulanan',
  'laporan-bulanan',
  true,
  10485760,  -- 10 MB
  ARRAY[
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',  -- .docx
    'application/msword',                                                         -- .doc
    'application/pdf'                                                             -- .pdf
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY[
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword',
    'application/pdf'
  ];


-- ============================================================
-- STEP 8: Storage Policies (izinkan upload & download)
-- ============================================================

-- Hapus policy lama jika ada
DROP POLICY IF EXISTS "laporan_public_read"    ON storage.objects;
DROP POLICY IF EXISTS "laporan_anon_insert"    ON storage.objects;
DROP POLICY IF EXISTS "laporan_anon_update"    ON storage.objects;
DROP POLICY IF EXISTS "laporan_anon_delete"    ON storage.objects;

-- Siapa saja bisa baca file (public)
CREATE POLICY "laporan_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'laporan-bulanan');

-- Siapa saja bisa upload (pakai anon key dari frontend)
CREATE POLICY "laporan_anon_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'laporan-bulanan');

-- Siapa saja bisa update (replace file)
CREATE POLICY "laporan_anon_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'laporan-bulanan');

-- Siapa saja bisa hapus file
CREATE POLICY "laporan_anon_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'laporan-bulanan');


-- ============================================================
-- STEP 9: RLS untuk tabel database
-- ============================================================

ALTER TABLE laporan_bulanan  ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs    ENABLE ROW LEVEL SECURITY;

-- Semua operasi diizinkan (kontrol akses dilakukan di sisi React)
DROP POLICY IF EXISTS "allow_all_laporan"       ON laporan_bulanan;
DROP POLICY IF EXISTS "allow_select_app_users"  ON app_users;
DROP POLICY IF EXISTS "allow_all_activity_logs" ON activity_logs;

CREATE POLICY "allow_all_laporan"
  ON laporan_bulanan FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "allow_select_app_users"
  ON app_users FOR SELECT USING (true);

CREATE POLICY "allow_all_activity_logs"
  ON activity_logs FOR ALL USING (true) WITH CHECK (true);


-- ============================================================
-- STEP 10: VERIFIKASI (jalankan setelah selesai)
-- ============================================================
-- Cek akun yang sudah dibuat:
-- SELECT id, nama, email, role, seksi_id FROM app_users ORDER BY role;

-- Cek bucket storage:
-- SELECT id, name, public, file_size_limit FROM storage.buckets WHERE id = 'laporan-bulanan';

-- Cek urutan seksi:
-- SELECT id, name, urutan_penggabungan FROM sections ORDER BY urutan_penggabungan;
