-- ==============================================
-- KODE SQL UNTUK MENU DATA SEKSI DAN SUBMENU
-- ==============================================
-- Copy dan jalankan kode ini di Supabase SQL Editor

-- 1. Tabel untuk Data Seksi/Organisasi
-- Tabel ini menyimpan informasi untuk Menu "Data Seksi" dan semua submenu-nya:
-- - Semua Seksi
-- - Seksi Inteldakim  
-- - Seksi Lalintalkim
-- - Seksi Tikim
-- - Subbag Tata Usaha

create table if not exists sections (
  id bigint generated by default as identity primary key,
  name text not null,                    -- Nama Seksi (contoh: "Seksi Inteldakim")
  alias text,                             -- Alias/Nama Lengkap (contoh: "Intelijen & Penindakan Keimigrasian")
  staff int default 0,                    -- Jumlah Personil
  programs int default 0,                 -- Jumlah Program
  performance int default 0,              -- Persentase Kinerja (0-100)
  icon text,                              -- SVG Path untuk Icon
  description text,                       -- Deskripsi Seksi
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Tabel untuk Menu Anggota (Members/Users Management)
-- Menyimpan data pegawai untuk menu "Anggota" di Administrasi
create table if not exists members (
  id bigint generated by default as identity primary key,
  nip text not null unique,               -- NIP Pegawai (Nomor Induk Pegawai)
  name text not null,                      -- Nama Lengkap
  email text,                              -- Email Dinas
  phone text,                              -- No. Telepon
  section text,                            -- Seksi/Bidang (Lalintalkim, Inteldakim, Tikim, Tata Usaha)
  role text default 'Staff',               -- Peran (Staff, Supervisor, Administrator)
  status text default 'Active',            -- Status (Active, Inactive)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default members data
insert into members (nip, name, role, section, status, email, phone)
values
  ('19850101 201001 1 001', 'Ari Dwiantoro', 'Administrator', 'Teknologi Informasi', 'Active', 'ari.dwiantoro@imigrasi.go.id', '0812-1111-1111'),
  ('19900202 201502 2 002', 'Siti Aminah', 'Staff', 'Lalintalkim', 'Active', 'siti.aminah@imigrasi.go.id', '0812-2222-2222'),
  ('19880303 201403 1 003', 'Budi Santoso', 'Supervisor', 'Inteldakim', 'Active', 'budi.santoso@imigrasi.go.id', '0812-3333-3333')
on conflict do nothing;

-- 6. Tabel untuk Profile Saya (User Profile)
-- Menyimpan data profil lengkap untuk menu "Profile Saya"
create table if not exists user_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint references members(id) on delete cascade,  -- Relasi ke tabel members
  nip text not null unique,               -- NIP (untuk lookup)
  name text not null,                      -- Nama Lengkap
  position text,                           -- Jabatan (contoh: "Analisis Keimigrasian Ahli Muda")
  rank text,                               -- Pangkat (contoh: "Penata (III/c)")
  email text,                              -- Email
  phone text,                              -- No. Telepon
  unit text,                               -- Unit Kerja (contoh: "Seksi Teknologi Informasi & Komunikasi")
  bio text,                                -- Biografi/Deskripsi Singkat
  photo_url text,                          -- URL Foto Profil (bisa Supabase Storage atau Base64)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default profile data (untuk user Administrator)
insert into user_profiles (nip, name, position, rank, email, phone, unit, bio)
values
  (
    '19850101 201001 1 001',
    'Administrator',
    'Analisis Keimigrasian Ahli Muda',
    'Penata (III/c)',
    'admin@imigrasi-pematangsiantar.go.id',
    '0812-3456-7890',
    'Seksi Teknologi Informasi & Komunikasi',
    'Berdedikasi dalam pengembangan sistem informasi manajemen keimigrasian yang modern dan akuntabel.'
  )
on conflict do nothing;

-- 7. CARA KERJA UNTUK MENU ANGGOTA:
-- - Tambah Anggota: INSERT INTO members (...) VALUES (...)
-- - Edit Anggota: UPDATE members SET ... WHERE id = ?
-- - Hapus Anggota: DELETE FROM members WHERE id = ?
-- - Lihat Semua: SELECT * FROM members ORDER BY name

-- 8. CARA KERJA UNTUK PROFILE SAYA:
-- - Load Profile: SELECT * FROM user_profiles WHERE nip = ?
-- - Update Profile: UPDATE user_profiles SET name = ?, position = ?, ... WHERE nip = ?
-- - Upload Foto: UPDATE user_profiles SET photo_url = ? WHERE nip = ?

-- 9. Verifikasi Data Members:
-- SELECT * FROM members ORDER BY name;

-- 10. Verifikasi Data Profile:
-- SELECT * FROM user_profiles WHERE nip = '19850101 201001 1 001';

-- ==============================================
-- 7. Tabel untuk Verifikasi & Review
-- ==============================================
-- Menyimpan dokumen yang perlu disetujui/direview
create table if not exists verification_documents (
  id bigint generated by default as identity primary key,
  doc_type text not null,                  -- Jenis Dokumen (Laporan Bulanan, Program Kerja, Anggaran, dll)
  title text not null,                      -- Judul Dokumen
  author text not null,                     -- Pengaju/Pembuat (Seksi/Unit)
  submitted_date date default current_date, -- Tanggal Pengajuan
  status text default 'pending',            -- Status (pending, approved, revision, rejected)
  priority text default 'Medium',           -- Prioritas (High, Medium, Low)
  target_view text,                         -- View/Route tujuan untuk membuka dokumen
  review_note text,                         -- Catatan Review/Feedback
  reviewed_by text,                         -- Nama Reviewer
  reviewed_at timestamp with time zone,     -- Waktu Review
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default verification documents
insert into verification_documents (doc_type, title, author, submitted_date, status, priority, target_view)
values
  ('Laporan Bulanan', 'Laporan Kinerja Januari 2026', 'Seksi Lalintalkim', '2026-01-08', 'pending', 'High', 'policy-brief'),
  ('Program Kerja', 'Operasi Gabungan TPI 2026', 'Seksi Inteldakim', '2026-01-09', 'pending', 'Medium', 'work-program-input'),
  ('Anggaran', 'Revisi Pagu DIPA 2026', 'Subbag Tata Usaha', '2026-01-10', 'approved', 'High', 'section-data'),
  ('Program Kerja', 'Pemeliharaan Server Simkim', 'Seksi Tikim', '2026-01-09', 'revision', 'Low', 'work-program-input')
on conflict do nothing;

-- ==============================================
-- 8. Tabel untuk Cetak & Arsip
-- ==============================================
-- Menyimpan laporan yang sudah dicetak/diekspor
create table if not exists archived_reports (
  id bigint generated by default as identity primary key,
  report_title text not null,               -- Judul Laporan (contoh: "Laporan Tahun 2025")
  report_type text not null,                -- Jenis (Annual Report, Monthly Report, Program Report)
  file_format text not null,                -- Format File (PDF, Word, Excel)
  file_url text,                            -- URL File di Supabase Storage
  file_path text,                           -- Path File di Storage
  file_size bigint,                         -- Ukuran File (bytes)
  year int,                                 -- Tahun Laporan
  month int,                                -- Bulan Laporan (jika monthly report)
  section text,                             -- Seksi Pembuat (optional)
  description text,                         -- Deskripsi Singkat
  archived_by text,                         -- Nama User yang Menyimpan
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default archived reports
insert into archived_reports (report_title, report_type, file_format, file_size, year, description)
values
  ('Laporan Tahun 2025', 'Annual Report', 'PDF', 2516582, 2025, 'Laporan tahunan kinerja KIM Kelas II TPI Pematang Siantar tahun 2025'),
  ('Laporan Tahun 2025', 'Annual Report', 'Word', 1887436, 2025, 'Laporan tahunan kinerja KIM Kelas II TPI Pematang Siantar tahun 2025 (format Word)')
on conflict do nothing;

-- ==============================================
-- CARA KERJA UNTUK VERIFIKASI & REVIEW:
-- ==============================================
-- 1. Lihat semua dokumen pending:
--    SELECT * FROM verification_documents WHERE status = 'pending' ORDER BY priority, submitted_date;

-- 2. Approve dokumen:
--    UPDATE verification_documents 
--    SET status = 'approved', reviewed_by = 'Nama Reviewer', reviewed_at = now(), review_note = 'Disetujui'
--    WHERE id = ?;

-- 3. Request revision:
--    UPDATE verification_documents 
--    SET status = 'revision', reviewed_by = 'Nama Reviewer', reviewed_at = now(), review_note = 'Mohon perbaiki bagian X'
--    WHERE id = ?;

-- 4. Reject dokumen:
--    UPDATE verification_documents 
--    SET status = 'rejected', reviewed_by = 'Nama Reviewer', reviewed_at = now(), review_note = 'Alasan penolakan'
--    WHERE id = ?;

-- ==============================================
-- CARA KERJA UNTUK CETAK & ARSIP:
-- ==============================================
-- 1. Tambah arsip baru (setelah upload file ke Supabase Storage):
--    INSERT INTO archived_reports (report_title, report_type, file_format, file_url, file_path, file_size, year, archived_by)
--    VALUES ('Laporan Jan 2026', 'Monthly Report', 'PDF', 'https://...', 'reports/jan-2026.pdf', 1234567, 2026, 'Admin');

-- 2. Lihat semua arsip:
--    SELECT * FROM archived_reports ORDER BY year DESC, month DESC;

-- 3. Lihat arsip berdasarkan tahun:
--    SELECT * FROM archived_reports WHERE year = 2025;

-- 4. Download file (gunakan file_url dari query):
--    File bisa didownload langsung dari URL yang tersimpan di field file_url

-- ==============================================
-- CATATAN PENTING:
-- ==============================================
-- Untuk storage file arsip, Anda perlu membuat bucket di Supabase Storage:
-- 1. Buka Supabase Dashboard > Storage
-- 2. Create bucket: 'archived-reports'
-- 3. Set bucket sebagai Public agar file bisa didownload
-- 4. Upload file ke bucket, simpan URL-nya di tabel archived_reports

-- 2. Insert Data Default untuk 4 Seksi
-- Data ini akan otomatis muncul di menu Data Seksi
insert into sections (name, alias, staff, programs, performance, icon, description)
values
  -- Seksi Inteldakim
  (
    'Seksi Inteldakim', 
    'Intelijen & Penindakan Keimigrasian', 
    24, 
    8, 
    92, 
    'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z', 
    'Bertanggung jawab atas pengawasan orang asing dan penegakan hukum keimigrasian di wilayah kerja Pematang Siantar.'
  ),
  
  -- Seksi Lalintalkim
  (
    'Seksi Lalintalkim', 
    'Lalu Lintas & Izin Tinggal Keimigrasian', 
    18, 
    6, 
    95, 
    'M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z', 
    'Melayani penerbitan paspor RI, izin tinggal warga negara asing, dan pelayanan keimigrasian lainnya.'
  ),
  
  -- Seksi Tikim
  (
    'Seksi Tikim', 
    'Teknologi Informasi & Komunikasi', 
    8, 
    4, 
    88, 
    'M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z', 
    'Mengelola sistem informasi manajemen keimigrasian, penyebaran informasi, dan pemeliharaan infrastruktur TI.'
  ),
  
  -- Subbag Tata Usaha
  (
    'Subbag Tata Usaha', 
    'Fasilitatif & Kepegawaian', 
    15, 
    7, 
    90, 
    'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4', 
    'Menangani urusan kepegawaian, keuangan, persuratan, dan urusan rumah tangga kantor.'
  )
on conflict do nothing;

-- 3. CARA KERJA:
-- Ketika Anda mengklik tombol "Edit" pada kartu seksi di aplikasi:
-- - Data akan disimpan menggunakan UPDATE query ke tabel sections
-- - Field yang dapat diedit: name, alias, staff, programs, performance, description
-- - Field updated_at akan otomatis diperbarui

-- 4. Contoh Query Update (otomatis dijalankan oleh aplikasi saat Anda klik "Simpan"):
-- UPDATE sections 
-- SET 
--   name = 'Nama Baru',
--   alias = 'Alias Baru',
--   staff = 25,
--   programs = 10,
--   performance = 95,
--   description = 'Deskripsi baru',
--   updated_at = now()
-- WHERE id = 1;

-- 5. Verifikasi Data (jalankan query ini untuk melihat semua data seksi):
-- SELECT * FROM sections ORDER BY id;

-- ==============================================
-- KODE SQL UNTUK MENU TULIS LAPORAN (POLICY BRIEF EDITOR)
-- ==============================================
-- Tabel untuk menyimpan konten laporan yang ditulis di PolicyBriefEditor
-- Mendukung auto-save agar konten tidak hilang

-- 1. Tabel untuk menyimpan konten laporan per section
create table if not exists policy_briefs (
  id bigint generated by default as identity primary key,
  report_id text not null,                    -- ID unik untuk setiap draft laporan (contoh: "draft-2026-01-30")
  section_id text not null,                   -- ID section (umum, maksud, ruang_lingkup, dll)
  content text,                               -- Konten HTML dari contentEditable
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Composite unique constraint untuk upsert
  unique(report_id, section_id)
);

-- 2. Tabel untuk menyimpan lampiran/attachment
create table if not exists policy_brief_attachments (
  id bigint generated by default as identity primary key,
  report_id text not null,                    -- Relasi ke report
  section_id text not null,                   -- Section tempat file di-upload
  file_name text not null,                     -- Nama file asli
  file_path text not null,                     -- Path di Supabase Storage
  file_size bigint,                            -- Ukuran file (bytes)
  file_type text,                              -- MIME type (image/jpeg, application/pdf, dll)
  public_url text,                             -- URL publik untuk akses file
  uploaded_by text,                            -- User yang upload (opsional)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Index untuk performa query
create index if not exists idx_policy_briefs_report_id on policy_briefs(report_id);
create index if not exists idx_policy_brief_attachments_report_id on policy_brief_attachments(report_id);

-- ==============================================
-- CARA KERJA MENU TULIS LAPORAN:
-- ==============================================

-- 1. AUTO-SAVE KONTEN (dilakukan otomatis setiap 1 detik setelah user berhenti mengetik):
--    INSERT INTO policy_briefs (report_id, section_id, content)
--    VALUES ('draft-current', 'umum', '<p>Konten HTML...</p>')
--    ON CONFLICT (report_id, section_id) 
--    DO UPDATE SET content = EXCLUDED.content, updated_at = now();

-- 2. LOAD DRAFT TERAKHIR (saat user membuka menu Tulis Laporan):
--    SELECT * FROM policy_briefs WHERE report_id = 'draft-current' ORDER BY section_id;

-- 3. UPLOAD LAMPIRAN:
--    a. Upload file ke Supabase Storage bucket 'policy-brief-files'
--    b. INSERT INTO policy_brief_attachments (report_id, section_id, file_name, file_path, file_size, file_type, public_url)
--       VALUES ('draft-current', 'lampiran', 'foto.jpg', 'lampiran/123_foto.jpg', 51200, 'image/jpeg', 'https://...');

-- 4. HAPUS LAMPIRAN:
--    a. DELETE FROM policy_brief_attachments WHERE id = ?
--    b. Hapus file dari Storage menggunakan file_path

-- 5. BUAT LAPORAN BARU:
--    Gunakan report_id baru (contoh: 'report-2026-01-30-001')

-- ==============================================
-- STORAGE BUCKET SETUP (Lakukan di Supabase Dashboard):
-- ==============================================
-- 1. Buka Supabase Dashboard > Storage
-- 2. Create new bucket: 'policy-brief-files'
-- 3. Set bucket public: true (untuk download/preview)
-- 4. Set policies:
--    - Allow authenticated users to upload
--    - Allow public read access

-- ==============================================
-- VERIFIKASI DATA:
-- ==============================================
-- Lihat semua drafts:
-- SELECT DISTINCT report_id, MAX(updated_at) as last_updated 
-- FROM policy_briefs 
-- GROUP BY report_id 
-- ORDER BY last_updated DESC;

-- Lihat konten satu report:
-- SELECT * FROM policy_briefs WHERE report_id = 'draft-current' ORDER BY section_id;

-- Lihat attachments:
-- SELECT * FROM policy_brief_attachments WHERE report_id = 'draft-current';
