-- ==============================================================
-- HORAS-IM: RBAC SCHEMA
-- Jalankan file ini di Supabase SQL Editor
-- Urutan eksekusi: file ini SETELAH supabase_schema.sql
-- ==============================================================

-- ==============================================================
-- 1. Update tabel sections: tambah kolom urutan_penggabungan
-- ==============================================================
ALTER TABLE sections
  ADD COLUMN IF NOT EXISTS urutan_penggabungan int DEFAULT 99;

-- Set urutan default berdasarkan nama
UPDATE sections SET urutan_penggabungan = 1 WHERE name ILIKE '%inteldakim%';
UPDATE sections SET urutan_penggabungan = 2 WHERE name ILIKE '%lalintalkim%';
UPDATE sections SET urutan_penggabungan = 3 WHERE name ILIKE '%tikim%';
UPDATE sections SET urutan_penggabungan = 4 WHERE name ILIKE '%tata usaha%';


-- ==============================================================
-- 2. Tabel app_users (sistem login RBAC)
-- ==============================================================
CREATE TABLE IF NOT EXISTS app_users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama            text NOT NULL,
  email           text NOT NULL UNIQUE,
  password_hash   text NOT NULL,          -- SHA-256 hex
  role            text NOT NULL CHECK (role IN ('super_admin','admin_seksi')),
  seksi_id        bigint REFERENCES sections(id) ON DELETE SET NULL,
  is_active       boolean DEFAULT true,
  last_login      timestamp with time zone,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL
);

-- Index untuk login cepat
CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);

-- ==============================================================
-- 3. Akun default
-- Password semua: Admin@2026  (hash SHA-256 hex)
-- Super Admin  → hash of 'Admin@2026'
-- Admin Seksi  → hash of 'Seksi@2026'
-- Catatan: hash dihitung sisi client; nilai di bawah adalah
--   SHA-256("Admin@2026") dan SHA-256("Seksi@2026") dalam hex
-- ==============================================================

-- Hitung hash dulu di sisi server (menggunakan pgcrypto)
-- Jika pgcrypto belum aktif, aktifkan dengan:
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Super Administrator',
  'superadmin@horas-im.local',
  encode(digest('Admin@2026', 'sha256'), 'hex'),
  'super_admin',
  NULL
WHERE NOT EXISTS (SELECT 1 FROM app_users WHERE email = 'superadmin@horas-im.local');

INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Inteldakim',
  'inteldakim@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%inteldakim%' LIMIT 1
ON CONFLICT (email) DO NOTHING;

INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Lalintalkim',
  'lalintalkim@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%lalintalkim%' LIMIT 1
ON CONFLICT (email) DO NOTHING;

INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Tikim',
  'tikim@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%tikim%' LIMIT 1
ON CONFLICT (email) DO NOTHING;

INSERT INTO app_users (nama, email, password_hash, role, seksi_id)
SELECT
  'Admin Tata Usaha',
  'tu@horas-im.local',
  encode(digest('Seksi@2026', 'sha256'), 'hex'),
  'admin_seksi',
  s.id
FROM sections s WHERE s.name ILIKE '%tata usaha%' LIMIT 1
ON CONFLICT (email) DO NOTHING;


-- ==============================================================
-- 4. Tabel laporan_bulanan
-- ==============================================================
CREATE TABLE IF NOT EXISTS laporan_bulanan (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seksi_id        bigint NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  bulan           int NOT NULL CHECK (bulan BETWEEN 1 AND 12),
  tahun           int NOT NULL CHECK (tahun >= 2020),

  -- File info
  file_name       text,
  file_path       text,                    -- path di Supabase Storage
  file_url        text,                    -- public URL
  file_size       bigint,                  -- bytes

  -- Status workflow
  status          text NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft','Dikirim','Perlu Revisi','Disetujui','Final')),

  -- Review
  catatan_revisi  text,
  submitted_at    timestamp with time zone,
  submitted_by    bigint REFERENCES app_users(id) ON DELETE SET NULL,
  reviewed_by     bigint REFERENCES app_users(id) ON DELETE SET NULL,
  approved_at     timestamp with time zone,

  -- Kunci final
  final_locked    boolean DEFAULT false,

  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL,

  -- Satu laporan per seksi per bulan per tahun
  UNIQUE(seksi_id, bulan, tahun)
);

CREATE INDEX IF NOT EXISTS idx_laporan_seksi_id  ON laporan_bulanan(seksi_id);
CREATE INDEX IF NOT EXISTS idx_laporan_status     ON laporan_bulanan(status);
CREATE INDEX IF NOT EXISTS idx_laporan_bulan_tahun ON laporan_bulanan(bulan, tahun);


-- ==============================================================
-- 5. Tabel activity_logs
-- ==============================================================
CREATE TABLE IF NOT EXISTS activity_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint REFERENCES app_users(id) ON DELETE SET NULL,
  user_name   text,
  action      text NOT NULL,              -- upload, submit, approve, revisi, finalisasi, login, logout
  entity_type text,                       -- laporan_bulanan, user, dll
  entity_id   bigint,
  detail      text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at DESC);


-- ==============================================================
-- 6. Row Level Security (RLS)
-- Aktifkan agar admin_seksi hanya bisa akses laporan miliknya
-- ==============================================================

-- Aktifkan RLS di laporan_bulanan
ALTER TABLE laporan_bulanan ENABLE ROW LEVEL SECURITY;

-- Policy: anon key bisa SELECT semua (untuk query dari app dengan anon key)
-- Pembatasan akses dilakukan di sisi aplikasi (RBAC logic di React)
CREATE POLICY IF NOT EXISTS "allow_select_laporan"
  ON laporan_bulanan FOR SELECT
  USING (true);

CREATE POLICY IF NOT EXISTS "allow_insert_laporan"
  ON laporan_bulanan FOR INSERT
  WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "allow_update_laporan"
  ON laporan_bulanan FOR UPDATE
  USING (true);

CREATE POLICY IF NOT EXISTS "allow_delete_laporan"
  ON laporan_bulanan FOR DELETE
  USING (true);

-- RLS app_users: hanya bisa SELECT (tidak bisa insert/update dari browser langsung)
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "allow_select_app_users"
  ON app_users FOR SELECT
  USING (true);

-- RLS activity_logs
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "allow_all_activity_logs"
  ON activity_logs FOR ALL
  USING (true);


-- ==============================================================
-- 7. Verifikasi
-- ==============================================================
-- Setelah menjalankan script ini, cek hasilnya:
-- SELECT id, nama, email, role, seksi_id FROM app_users ORDER BY role;
-- SELECT id, name, urutan_penggabungan FROM sections ORDER BY urutan_penggabungan;
