-- ============================================================
-- ARSIP & DOKUMEN — Schema Upgrade (Non-Breaking)
-- Jalankan di Supabase SQL Editor
-- Aman: semua ADD COLUMN IF NOT EXISTS — data lama tidak hilang
-- ============================================================

-- 1. Upgrade tabel archived_reports
ALTER TABLE archived_reports
  ADD COLUMN IF NOT EXISTS bulan       int,
  ADD COLUMN IF NOT EXISTS seksi       text,
  ADD COLUMN IF NOT EXISTS file_name   text,
  ADD COLUMN IF NOT EXISTS file_path   text,
  ADD COLUMN IF NOT EXISTS archived_by_id text,
  ADD COLUMN IF NOT EXISTS is_deleted  boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS deleted_at  timestamptz,
  ADD COLUMN IF NOT EXISTS version     int DEFAULT 1,
  ADD COLUMN IF NOT EXISTS source      text DEFAULT 'manual';
  -- source: 'manual' | 'auto_export'

-- 2. Tabel log aktivitas arsip
CREATE TABLE IF NOT EXISTS archive_activity_logs (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_id   bigint REFERENCES archived_reports(id) ON DELETE SET NULL,
  user_id      text,
  user_name    text,
  action       text NOT NULL, -- 'upload','download','delete','restore','rename','preview'
  detail       text,
  created_at   timestamptz DEFAULT now() NOT NULL
);

-- 3. Indexes untuk performa query
CREATE INDEX IF NOT EXISTS idx_archived_year_month
  ON archived_reports(year, month);
CREATE INDEX IF NOT EXISTS idx_archived_seksi
  ON archived_reports(seksi);
CREATE INDEX IF NOT EXISTS idx_archived_not_deleted
  ON archived_reports(is_deleted);
CREATE INDEX IF NOT EXISTS idx_archive_logs_archive_id
  ON archive_activity_logs(archive_id);
CREATE INDEX IF NOT EXISTS idx_archive_logs_created
  ON archive_activity_logs(created_at DESC);

-- 4. Pastikan kolom lama tidak null di existing records
UPDATE archived_reports SET is_deleted = false WHERE is_deleted IS NULL;
UPDATE archived_reports SET source = 'manual' WHERE source IS NULL;
UPDATE archived_reports SET version = 1 WHERE version IS NULL;

-- 5. RLS — biarkan akses penuh (aplikasi sudah handle RBAC di frontend)
ALTER TABLE archived_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "archived_reports_all" ON archived_reports;
CREATE POLICY "archived_reports_all"
  ON archived_reports FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE archive_activity_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "archive_logs_all" ON archive_activity_logs;
CREATE POLICY "archive_logs_all"
  ON archive_activity_logs FOR ALL USING (true) WITH CHECK (true);

-- 6. Storage bucket 'archived-reports'
-- Jalankan query ini HANYA jika bucket belum ada di Supabase Storage:
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'archived-reports',
  'archived-reports',
  true,
  52428800, -- 50MB limit
  ARRAY['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword']
) ON CONFLICT (id) DO NOTHING;

-- Storage Policy — allow all (handled by app)
INSERT INTO storage.policies (name, bucket_id, operation, definition)
VALUES
  ('archived_reports_select', 'archived-reports', 'SELECT', 'true'),
  ('archived_reports_insert', 'archived-reports', 'INSERT', 'true'),
  ('archived_reports_update', 'archived-reports', 'UPDATE', 'true'),
  ('archived_reports_delete', 'archived-reports', 'DELETE', 'true')
ON CONFLICT DO NOTHING;

-- 7. Verifikasi
SELECT
  (SELECT COUNT(*) FROM archived_reports) AS total_arsip,
  (SELECT COUNT(*) FROM archived_reports WHERE is_deleted = false) AS arsip_aktif,
  (SELECT COUNT(*) FROM archive_activity_logs) AS total_log_aktivitas;
