-- ============================================================
-- HORAS-IM: SQL SETUP LENGKAP
-- Jalankan file ini di Supabase SQL Editor
-- Mencakup: app_users, sections, laporan_bulanan,
--           Storage Bucket, Policies, RLS
-- ============================================================


-- ============================================================
-- STEP 1: Tabel app_users — tambah kolom yang diperlukan
-- ============================================================
ALTER TABLE app_users
  ADD COLUMN IF NOT EXISTS nip          text,
  ADD COLUMN IF NOT EXISTS phone        text,
  ADD COLUMN IF NOT EXISTS is_active    boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS last_login   timestamp with time zone,
  ADD COLUMN IF NOT EXISTS created_at   timestamp with time zone DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at   timestamp with time zone DEFAULT now();


-- ============================================================
-- STEP 2: Tabel sections (pastikan sudah ada)
-- ============================================================
CREATE TABLE IF NOT EXISTS sections (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 text NOT NULL,
  alias                text,
  urutan_penggabungan  int DEFAULT 99,
  created_at           timestamp with time zone DEFAULT now()
);

-- Insert seksi default jika belum ada
INSERT INTO sections (name, alias, urutan_penggabungan)
VALUES
  ('Seksi Inteldakim',       'inteldakim',   1),
  ('Seksi Lalintalkim',      'lalintalkim',  2),
  ('Seksi Tikim',            'tikim',        3),
  ('Subbag Tata Usaha',      'tu',           4)
ON CONFLICT DO NOTHING;


-- ============================================================
-- STEP 3: Tabel laporan_bulanan
-- ============================================================
CREATE TABLE IF NOT EXISTS laporan_bulanan (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seksi_id        bigint NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  bulan           int NOT NULL CHECK (bulan BETWEEN 1 AND 12),
  tahun           int NOT NULL CHECK (tahun >= 2020),

  file_name       text,
  file_path       text,
  file_url        text,
  file_size       bigint,
  file_type       text,       -- 'docx' | 'doc' | 'pdf'

  status          text NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft','Dikirim','Perlu Revisi','Disetujui','Final')),

  catatan_revisi  text,
  submitted_at    timestamp with time zone,
  submitted_by    bigint REFERENCES app_users(id) ON DELETE SET NULL,
  reviewed_by     bigint REFERENCES app_users(id) ON DELETE SET NULL,
  approved_at     timestamp with time zone,
  final_locked    boolean DEFAULT false,

  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL,

  UNIQUE(seksi_id, bulan, tahun)
);

CREATE INDEX IF NOT EXISTS idx_laporan_seksi_id    ON laporan_bulanan(seksi_id);
CREATE INDEX IF NOT EXISTS idx_laporan_status       ON laporan_bulanan(status);
CREATE INDEX IF NOT EXISTS idx_laporan_bulan_tahun  ON laporan_bulanan(bulan, tahun);


-- ============================================================
-- STEP 4: Storage Bucket 'laporan-bulanan'
-- Bucket public agar URL file bisa diakses langsung
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'laporan-bulanan',
  'laporan-bulanan',
  true,
  10485760,   -- 10 MB
  ARRAY[
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword',
    'application/pdf'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public              = true,
  file_size_limit     = 10485760,
  allowed_mime_types  = ARRAY[
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword',
    'application/pdf'
  ];


-- ============================================================
-- STEP 5: Storage Policies untuk bucket laporan-bulanan
-- ============================================================

-- Bersihkan policy lama
DROP POLICY IF EXISTS "laporan_public_read"   ON storage.objects;
DROP POLICY IF EXISTS "laporan_anon_insert"   ON storage.objects;
DROP POLICY IF EXISTS "laporan_anon_update"   ON storage.objects;
DROP POLICY IF EXISTS "laporan_anon_delete"   ON storage.objects;

-- Siapa saja bisa baca (public URL)
CREATE POLICY "laporan_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'laporan-bulanan');

-- Siapa saja bisa upload (termasuk anon key dari browser)
CREATE POLICY "laporan_anon_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'laporan-bulanan');

-- Siapa saja bisa replace/overwrite file
CREATE POLICY "laporan_anon_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'laporan-bulanan');

-- Siapa saja bisa hapus file lama
CREATE POLICY "laporan_anon_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'laporan-bulanan');


-- ============================================================
-- STEP 6: Row Level Security (RLS) — Tabel database
-- ============================================================
ALTER TABLE laporan_bulanan  ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users        ENABLE ROW LEVEL SECURITY;

-- Bersihkan policy lama
DROP POLICY IF EXISTS "allow_all_laporan"           ON laporan_bulanan;
DROP POLICY IF EXISTS "allow_select_app_users"      ON app_users;
DROP POLICY IF EXISTS "allow_update_app_users"      ON app_users;
DROP POLICY IF EXISTS "allow_insert_app_users"      ON app_users;
DROP POLICY IF EXISTS "allow_delete_app_users"      ON app_users;

-- laporan_bulanan: izinkan semua operasi (kontrol akses di React)
CREATE POLICY "allow_all_laporan"
  ON laporan_bulanan FOR ALL
  USING (true)
  WITH CHECK (true);

-- app_users: izinkan SELECT untuk semua (login & load profil)
CREATE POLICY "allow_select_app_users"
  ON app_users FOR SELECT
  USING (true);

-- app_users: izinkan UPDATE (edit profil, ganti password, last_login)
CREATE POLICY "allow_update_app_users"
  ON app_users FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- app_users: izinkan INSERT (tambah anggota baru oleh super admin)
CREATE POLICY "allow_insert_app_users"
  ON app_users FOR INSERT
  WITH CHECK (true);

-- app_users: izinkan DELETE (hapus akun oleh super admin)
CREATE POLICY "allow_delete_app_users"
  ON app_users FOR DELETE
  USING (true);


-- ============================================================
-- STEP 7: activity_logs (log upload, login, review)
-- ============================================================
CREATE TABLE IF NOT EXISTS activity_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint REFERENCES app_users(id) ON DELETE SET NULL,
  user_name   text,
  action      text NOT NULL,
  entity_type text,
  entity_id   bigint,
  detail      text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_activity_logs" ON activity_logs;
CREATE POLICY "allow_all_activity_logs"
  ON activity_logs FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user    ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at DESC);


-- ============================================================
-- STEP 8: Akun default — jalankan HANYA SEKALI
-- Ganti password_hash dengan hash SHA-256 dari password Anda
-- SHA-256("Admin@2026") = hash yang digunakan AuthContext
--
-- Cara generate hash:
--   Di browser console: (async () => {
--     const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode('Admin@2026'));
--     console.log([...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join(''));
--   })()
-- ============================================================

-- Contoh insert akun super admin (sesuaikan hash-nya):
-- INSERT INTO app_users (nama, email, password_hash, role, is_active)
-- VALUES ('Super Administrator', 'superadmin@horas-im.local', '<SHA256_HASH_DISINI>', 'super_admin', true)
-- ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- STEP 9: VERIFIKASI — Jalankan query ini setelah setup selesai
-- ============================================================

-- Cek bucket yang sudah dibuat:
-- SELECT id, name, public, file_size_limit FROM storage.buckets WHERE id = 'laporan-bulanan';

-- Cek tabel laporan_bulanan:
-- SELECT COUNT(*) FROM laporan_bulanan;

-- Cek kolom nip/phone/is_active di app_users:
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_name = 'app_users' AND column_name IN ('nip', 'phone', 'is_active', 'last_login');

-- Cek akun yang terdaftar:
-- SELECT id, nama, email, role, nip, phone, seksi_id, is_active FROM app_users ORDER BY role;

-- Cek policies storage:
-- SELECT policyname, cmd FROM pg_policies WHERE tablename = 'objects';
