import { useState } from 'react';

const CreateReport = ({ onCancel }) => {
    const [formData, setFormData] = useState({
        judul: '',
        jenis: 'Bulanan',
        seksi: 'Lalintalkim',
        bulan: new Date().getMonth().toString(),
        tahun: new Date().getFullYear().toString(),
        ringkasan: '',
        file: null
    });

    const [isSubmitting, setIsSubmitting] = useState(false);
    const [showSuccess, setShowSuccess] = useState(false);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setFormData(prev => ({ ...prev, file: e.target.files[0] }));
        }
    };

    const generateReportFile = () => {
        // Mocking report generation
        const content = `
      LAPORAN ${formData.jenis.toUpperCase()}
      KANTOR IMIGRASI KELAS II TPI PEMATANGSIANTAR
      
      Judul: ${formData.judul}
      Seksi: ${formData.seksi}
      Periode: ${formData.bulan}/${formData.tahun}
      
      Ringkasan:
      ${formData.ringkasan}
      
      Generated by HORAS-IM System
    `;

        const blob = new Blob([content], { type: 'text/plain' });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", `Laporan_${formData.seksi}_${formData.bulan}_${formData.tahun}.txt`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        setIsSubmitting(true);

        // Simulate API call
        setTimeout(() => {
            setIsSubmitting(false);
            setShowSuccess(true);
        }, 1500);
    };

    const months = [
        'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
        'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
    ];

    const years = [2026, 2025, 2024, 2023];

    if (showSuccess) {
        return (
            <div className="bg-white rounded-xl shadow-lg border border-gray-100 p-8 text-center max-w-lg mx-auto mt-10">
                <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                    <svg className="w-10 h-10 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                </div>
                <h2 className="text-2xl font-bold text-gray-800 mb-2">Laporan Berhasil Disimpan!</h2>
                <p className="text-gray-600 mb-8">
                    Laporan Anda telah berhasil disubmit ke sistem. Anda dapat mengunduh bukti laporan ini.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <button
                        onClick={generateReportFile}
                        className="px-6 py-2.5 bg-imigrasi-navy text-white rounded-lg hover:bg-blue-900 transition-colors flex items-center justify-center gap-2"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        Download Bukti (PDF/Txt)
                    </button>
                    <button
                        onClick={onCancel}
                        className="px-6 py-2.5 bg-white border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
                    >
                        Kembali ke Dashboard
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden">
            <div className="p-6 border-b border-gray-100 bg-gradient-to-r from-gray-50 to-white">
                <h2 className="text-xl font-bold text-imigrasi-navy">Buat Laporan Baru</h2>
                <p className="text-sm text-gray-500 mt-1">Isi formulir berikut untuk membuat laporan bulanan seksi Anda.</p>
            </div>

            <form onSubmit={handleSubmit} className="p-8 space-y-6">
                {/* Judul Laporan */}
                <div>
                    <label htmlFor="judul" className="block text-sm font-semibold text-gray-700 mb-1.5">Judul Laporan</label>
                    <input
                        type="text"
                        id="judul"
                        name="judul"
                        required
                        value={formData.judul}
                        onChange={handleChange}
                        placeholder="Contoh: Laporan Bulanan Seksi Lalintalkim Januari 2026"
                        className="w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-imigrasi-blue/20 focus:border-imigrasi-blue outline-none transition-all"
                    />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Jenis Laporan */}
                    <div>
                        <label htmlFor="jenis" className="block text-sm font-semibold text-gray-700 mb-1.5">Jenis Laporan</label>
                        <select
                            id="jenis"
                            name="jenis"
                            value={formData.jenis}
                            onChange={handleChange}
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-imigrasi-blue/20 focus:border-imigrasi-blue outline-none transition-all"
                        >
                            <option value="Bulanan">Laporan Bulanan</option>
                            <option value="Triwulan">Laporan Triwulan</option>
                            <option value="Semester">Laporan Semester</option>
                            <option value="Tahunan">Laporan Tahunan</option>
                            <option value="Insidentil">Laporan Insidentil</option>
                        </select>
                    </div>

                    {/* Seksi / Bidang */}
                    <div>
                        <label htmlFor="seksi" className="block text-sm font-semibold text-gray-700 mb-1.5">Seksi / Bidang</label>
                        <select
                            id="seksi"
                            name="seksi"
                            value={formData.seksi}
                            onChange={handleChange}
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-imigrasi-blue/20 focus:border-imigrasi-blue outline-none transition-all"
                        >
                            <option value="Lalintalkim">Lalu Lintas Keimigrasian</option>
                            <option value="Inteldakim">Intelijen dan Penindakan Keimigrasian</option>
                            <option value="Tikim">Teknologi Informasi dan Komunikasi Keimigrasian</option>
                            <option value="Tata Usaha">Tata Usaha</option>
                        </select>
                    </div>
                </div>

                {/* Periode Laporan */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <label htmlFor="bulan" className="block text-sm font-semibold text-gray-700 mb-1.5">Bulan</label>
                        <select
                            id="bulan"
                            name="bulan"
                            value={formData.bulan}
                            onChange={handleChange}
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-imigrasi-blue/20 focus:border-imigrasi-blue outline-none transition-all"
                        >
                            {months.map((month, index) => (
                                <option key={index} value={index}>{month}</option>
                            ))}
                        </select>
                    </div>
                    <div>
                        <label htmlFor="tahun" className="block text-sm font-semibold text-gray-700 mb-1.5">Tahun</label>
                        <select
                            id="tahun"
                            name="tahun"
                            value={formData.tahun}
                            onChange={handleChange}
                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-imigrasi-blue/20 focus:border-imigrasi-blue outline-none transition-all"
                        >
                            {years.map((year) => (
                                <option key={year} value={year}>{year}</option>
                            ))}
                        </select>
                    </div>
                </div>

                {/* Ringkasan */}
                <div>
                    <label htmlFor="ringkasan" className="block text-sm font-semibold text-gray-700 mb-1.5">Ringkasan Kegiatan (Executive Summary)</label>
                    <textarea
                        id="ringkasan"
                        name="ringkasan"
                        rows="5"
                        value={formData.ringkasan}
                        onChange={handleChange}
                        placeholder="Tuliskan ringkasan singkat mengenai kegiatan yang dilaporkan..."
                        className="w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-lg focus:ring-2 focus:ring-imigrasi-blue/20 focus:border-imigrasi-blue outline-none transition-all resize-none"
                    ></textarea>
                </div>

                {/* File Upload */}
                <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-1.5">Upload File Laporan (PDF/Excel)</label>
                    <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-lg hover:bg-gray-50 hover:border-imigrasi-blue/50 transition-colors cursor-pointer relative group">
                        <input
                            type="file"
                            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                            onChange={handleFileChange}
                            accept=".pdf,.xlsx,.xls,.doc,.docx"
                        />
                        <div className="space-y-1 text-center">
                            <svg className="mx-auto h-12 w-12 text-gray-400 group-hover:text-imigrasi-blue transition-colors" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                            <div className="flex text-sm text-gray-600 justify-center">
                                <span className="relative cursor-pointer bg-white rounded-md font-medium text-imigrasi-blue hover:text-blue-700">
                                    {formData.file ? formData.file.name : 'Upload a file'}
                                </span>
                                {!formData.file && <p className="pl-1">or drag and drop</p>}
                            </div>
                            <p className="text-xs text-gray-500">
                                PDF, Excel, Word up to 10MB
                            </p>
                        </div>
                    </div>
                </div>

                {/* Buttons */}
                <div className="flex justify-end gap-3 pt-6 border-t border-gray-100">
                    <button
                        type="button"
                        onClick={onCancel}
                        className="px-5 py-2.5 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 hover:text-gray-900 transition-colors focus:ring-2 focus:ring-offset-2 focus:ring-gray-200"
                    >
                        Batal
                    </button>
                    <button
                        type="submit"
                        disabled={isSubmitting}
                        className={`px-6 py-2.5 text-sm font-medium text-white bg-imigrasi-navy rounded-lg hover:bg-blue-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-imigrasi-blue transition-all shadow-lg shadow-blue-900/20 ${isSubmitting ? 'opacity-75 cursor-wait' : ''}`}
                    >
                        {isSubmitting ? (
                            <span className="flex items-center gap-2">
                                <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                Menyimpan...
                            </span>
                        ) : 'Simpan Laporan'}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default CreateReport;
